on:
    release:
        types: [created]

permissions:
    contents: write
    packages: write

jobs:
    release-matrix:
        name: Release go binaries
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, windows]
                goarch: ["386", amd64]
        steps:
            - uses: actions/checkout@v4
            - uses: wangyoucao577/go-release-action@v1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                goos: ${{ matrix.goos }}
                goarch: ${{ matrix.goarch }}
                goversion: "https://go.dev/dl/go1.24.3.linux-amd64.tar.gz"
                project_path: "."
                binary_name: "program"
                ldflags: "-s -w"
        